# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Cheesy Title"
description: > # this means to ignore newlines until "email:"
   Mostly stuff about Adobe Experience Manager

email: justin@justinedelson.com
#blog logo
logo: "/assets/images/ct_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Justin Edelson'
author: 'Justin Edelson'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.justinedelson.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@justinedelson'

#fill in disqus shortname to use disqus
disqus: cheesytitle

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/justinedelson
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://www.linkedin.com/in/justinedelson
    desc: View my profile on LinkedIn
    share_url: https://www.linkedin.com/shareArticle?mini=true
    share_title: "&amp;title="
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/justinedelson
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
